name: IoTYYJ
favicon: null
layout_spectrum: 0.66741
typography_spectrum: 0.4129045200534165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#a0d1ca'
    - '#00999e'
    - '#fea45e'
  brandStrength: 0.17768948059529066
  lightness: 0.01890383055433631
  saturation: 0.23348936019465327
  rhythmicContrast: 0.2890325428452343
purpose: []
