name: IoTYYJ
favicon: null
layout_spectrum: 0.7325220035854727
typography_spectrum: 0.4129045200534165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.17768948059529066
  lightness: 0.01890383055433631
  saturation: 0.23348936019465327
  rhythmicContrast: 0.2890325428452343
purpose: []
